### ISSUE TITLE
Cannot cast integer columns

### ISSUE THREAD

**Issue by asafbrukarz** [solidsnack/GraphpostgresQL#5]
When searching against an integer primary key column, I receive: 

```
ERROR:  type "integer" does not exist
```

This is related to: `select '396'::"integer";`, rather than `select '396'::integer;` (which works correctly)

**Comment by solidsnack** [comment]
Let me know if the latest push to master fixes this for you and I'll close this one.

**Comment by asafbrukarz** [comment]
It has fixed the error that was thrown.

The only issue I have now is that using `run`, I get no results. 

If I try something simple like:

``` sql
SELECT graphql.to_sql($$
companies(396) {name}
$$);
```

I get:

``` sql
                       to_sql
----------------------------------------------------
 SELECT to_json("sub/1") AS companies              +
   FROM companies,                                 +
        LATERAL (                                  +
          SELECT companies.name                    +
        ) AS "sub/1"                               +
  WHERE ((companies.id) = (CAST('396' AS integer)))
(1 row)
```

If I copy and paste this manually I receive:

```
              companies
--------------------------------------
 {"name":"Sample Company"}
(1 row)
```

However, If I use `run`, I receive:

```
 run
-----
 []
(1 row)
```

**Comment by solidsnack** [comment]
I'm not sure why `FOUND` [isn't set](https://github.com/solidsnack/GraphpostgresQL/commit/3261a7b92a382ea5618c84541a1a57c5a872592f#diff-a5c83364c70cc6104c2c39a67d9629a6L138) but there's more than one way to do it.

**Comment by asafbrukarz** [comment]
That commit has fixed the issue! Great work.
