### ISSUE TITLE
psql:graphql.sql:334: ERROR:  too many parameters specified for RAISE

### ISSUE THREAD

**Issue by sivanand131** [solidsnack/GraphpostgresQL#7]
Getting the following error while loading the graphql schema itself.

**psql:graphql.sql:334: ERROR:  too many parameters specified for RAISE**

No changes done to the graphql.sql as of now; and using psql 9.6.2 version on Mac OS. Please suggest.

Thank you, Siva.

**Comment by solidsnack** [comment]
Fixed in 8756fce

This GraphQL implementation is very old and probably doesn't much resemble the current spec. There are others out there for Postgres.

**Comment by sivanand131** [comment]
Thanks Jason for your quick fix; it works fine now..

Can you please name a few which are based on the current spec and which are latest and good for production too?
